# Generated by Django 6.1 on 2026-09-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_skill_alter_experience_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, default='lucide:code', max_length=64),
        ),
    ]
