# Generated by Django 6.1 on 2026-09-13 16:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_skill_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('started_at', models.PositiveIntegerField(blank=True, null=True)),
                ('ended_at', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
